extern const GeoLayout test_area_1_geo[];
extern const GeoLayout test_area_1[];
extern const Collision test_area_1_collision[];
extern const MacroObject test_area_1_macro_objs[];
extern Lights1 test_dl_ground_lights;
extern Lights1 test_dl_dirt_lights;
extern u8 test_dl_Grass_SM64_Texture_ci8[];
extern u8 test_dl_Grass_SM64_Texture_pal_rgba16[];
extern u8 test_dl_Dirt_SM64_Texture_ci8[];
extern u8 test_dl_Dirt_SM64_Texture_pal_rgba16[];
extern Vtx test_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx test_dl_Plane_mesh_layer_1_vtx_0[566];
extern Gfx test_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx test_dl_Plane_mesh_layer_1_vtx_1[181];
extern Gfx test_dl_Plane_mesh_layer_1_tri_1[];
extern Gfx mat_test_dl_ground[];
extern Gfx mat_revert_test_dl_ground[];
extern Gfx mat_test_dl_dirt[];
extern Gfx mat_revert_test_dl_dirt[];
extern Gfx test_dl_Plane_mesh_layer_1[];
